'''
vector database(FAISS):
face ai semntic search till now we have 
embedding generated by sentence tranfomer
using chunks.
but suppose if chunks are 1000
and if 1 vector maps to 1 chunks at a tym.
1000 vector(100 of no.)
we need a specialized database to store vector.

why we can not use sqlite oe mysql??
in order to mysql and sqlite we need sql
and sql we write query
select* from <table> where text like "binary"
but if match the text not meaning.

which is the most efficicnetly searching algo.
no result found it becuse my sql does not store meaniing

FAIIS: will stroing the data it also the meaning in form
vectors and it return top k matching element,by  using nearest neighbour
algo.

when you create vector
1.index.faiss
2.index.pkl'''

from langchain_community.vectorstores import FAISS
#from utils.embedding import EMBEDDING_MODEL
class VectorStore:

    def __init__(self,embedding_model):
        self.embedding_model= embedding_model

    def create_vector_store(self,chunks) :
        '''
        this wil create the vector database using chunks'''
        vector_db=FAISS.from_documents(
            documents=chunks,
            embedding=self.embedding_model
        )   
        return vector_db
    def save(self,vector_db,path='vector_db'):
        '''
        this methods will all embedding in vector form inside localpath.
        '''

        vector_db.save_local(path)

    def load(self,path='vector_db'):
        return FAISS.load_local(
            path,
            self.embedding_model,
            allow_dangerous_deserilization=True
        )    